# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: craftpath/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63raftpath/v1/common.proto\x12\x0c\x63raftpath.v1\"$\n\x08\x46raction\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x0b\n\x03\x64\x65n\x18\x02 \x01(\r\"\x89\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x31\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32 .craftpath.v1.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'craftpath.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERROR_DETAILSENTRY._options = None
  _ERROR_DETAILSENTRY._serialized_options = b'8\001'
  _FRACTION._serialized_start=43
  _FRACTION._serialized_end=79
  _ERROR._serialized_start=82
  _ERROR._serialized_end=219
  _ERROR_DETAILSENTRY._serialized_start=173
  _ERROR_DETAILSENTRY._serialized_end=219
# @@protoc_insertion_point(module_scope)
