# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: craftpath/v1/item.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63raftpath/v1/item.proto\x12\x0c\x63raftpath.v1\"X\n\x14\x41\x66\x66ixTierConstraints\x12\x0c\n\x04tier\x18\x01 \x01(\r\x12\x32\n\x06\x62ounds\x18\x02 \x01(\x0e\x32\".craftpath.v1.AffixTierLevelBounds\"g\n\x0e\x41\x66\x66ixSpecifier\x12\x10\n\x08\x61\x66\x66ix_id\x18\x01 \x01(\r\x12\x11\n\tfractured\x18\x02 \x01(\x08\x12\x30\n\x04tier\x18\x03 \x01(\x0b\x32\".craftpath.v1.AffixTierConstraints\"\xe7\x01\n\x0cItemSnapshot\x12\x12\n\nitem_level\x18\x01 \x01(\r\x12(\n\x06rarity\x18\x02 \x01(\x0e\x32\x18.craftpath.v1.ItemRarity\x12\x0f\n\x07\x62\x61se_id\x18\x03 \x01(\r\x12-\n\x07\x61\x66\x66ixes\x18\x04 \x03(\x0b\x32\x1c.craftpath.v1.AffixSpecifier\x12\x11\n\tcorrupted\x18\x05 \x01(\x08\x12\x17\n\x0f\x61llowed_sockets\x18\x06 \x01(\r\x12-\n\x07sockets\x18\x07 \x03(\x0b\x32\x1c.craftpath.v1.AffixSpecifier*\x86\x01\n\nItemRarity\x12\x1b\n\x17ITEM_RARITY_UNSPECIFIED\x10\x00\x12\x16\n\x12ITEM_RARITY_NORMAL\x10\x01\x12\x15\n\x11ITEM_RARITY_MAGIC\x10\x02\x12\x14\n\x10ITEM_RARITY_RARE\x10\x03\x12\x16\n\x12ITEM_RARITY_UNIQUE\x10\x04*\x87\x01\n\x14\x41\x66\x66ixTierLevelBounds\x12\'\n#AFFIX_TIER_LEVEL_BOUNDS_UNSPECIFIED\x10\x00\x12!\n\x1d\x41\x46\x46IX_TIER_LEVEL_BOUNDS_EXACT\x10\x01\x12#\n\x1f\x41\x46\x46IX_TIER_LEVEL_BOUNDS_MINIMUM\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'craftpath.v1.item_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMRARITY._serialized_start=471
  _ITEMRARITY._serialized_end=605
  _AFFIXTIERLEVELBOUNDS._serialized_start=608
  _AFFIXTIERLEVELBOUNDS._serialized_end=743
  _AFFIXTIERCONSTRAINTS._serialized_start=41
  _AFFIXTIERCONSTRAINTS._serialized_end=129
  _AFFIXSPECIFIER._serialized_start=131
  _AFFIXSPECIFIER._serialized_end=234
  _ITEMSNAPSHOT._serialized_start=237
  _ITEMSNAPSHOT._serialized_end=468
# @@protoc_insertion_point(module_scope)
