# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: craftpath/v1/presets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63raftpath/v1/presets.proto\x12\x0c\x63raftpath.v1\"/\n\nPresetInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xa4\x01\n\nPresetList\x12\x31\n\x0fmatrix_builders\x18\x01 \x03(\x0b\x32\x18.craftpath.v1.PresetInfo\x12\x30\n\x0epath_analyzers\x18\x02 \x03(\x0b\x32\x18.craftpath.v1.PresetInfo\x12\x31\n\x0fgroup_analyzers\x18\x03 \x03(\x0b\x32\x18.craftpath.v1.PresetInfo*b\n\x13MatrixBuilderPreset\x12%\n!MATRIX_BUILDER_PRESET_UNSPECIFIED\x10\x00\x12$\n MATRIX_BUILDER_PRESET_HAPPY_PATH\x10\x01*\xb8\x02\n\x1bStatisticAnalyzerPathPreset\x12.\n*STATISTIC_ANALYZER_PATH_PRESET_UNSPECIFIED\x10\x00\x12\x35\n1STATISTIC_ANALYZER_PATH_PRESET_UNIQUE_PATH_CHANCE\x10\x01\x12\x39\n5STATISTIC_ANALYZER_PATH_PRESET_UNIQUE_PATH_EFFICIENCY\x10\x02\x12\x33\n/STATISTIC_ANALYZER_PATH_PRESET_UNIQUE_PATH_COST\x10\x03\x12\x42\n>STATISTIC_ANALYZER_PATH_PRESET_UNIQUE_PATH_CHANCE_MEMORY_HEAVY\x10\x04*\xf5\x01\n$StatisticAnalyzerCurrencyGroupPreset\x12\x38\n4STATISTIC_ANALYZER_CURRENCY_GROUP_PRESET_UNSPECIFIED\x10\x00\x12\x42\n>STATISTIC_ANALYZER_CURRENCY_GROUP_PRESET_CURRENCY_GROUP_CHANCE\x10\x01\x12O\nKSTATISTIC_ANALYZER_CURRENCY_GROUP_PRESET_CURRENCY_GROUP_CHANCE_MEMORY_HEAVY\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'craftpath.v1.presets_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIXBUILDERPRESET._serialized_start=260
  _MATRIXBUILDERPRESET._serialized_end=358
  _STATISTICANALYZERPATHPRESET._serialized_start=361
  _STATISTICANALYZERPATHPRESET._serialized_end=673
  _STATISTICANALYZERCURRENCYGROUPPRESET._serialized_start=676
  _STATISTICANALYZERCURRENCYGROUPPRESET._serialized_end=921
  _PRESETINFO._serialized_start=44
  _PRESETINFO._serialized_end=91
  _PRESETLIST._serialized_start=94
  _PRESETLIST._serialized_end=258
# @@protoc_insertion_point(module_scope)
