# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import polars as pl


class Animal:
    class Dog(Animal):
        __match_args__ = ("says",)
        @property
        def says(self) -> builtins.str: ...
        def __new__(cls, says: builtins.str) -> Animal.Dog: ...

    class Cat(Animal):
        __match_args__ = ("jumps",)
        @property
        def jumps(self) -> builtins.int: ...
        def __new__(cls, jumps: builtins.int) -> Animal.Cat: ...

    class Bird(Animal):
        __match_args__ = ("swims",)
        @property
        def swims(self) -> builtins.int: ...
        def __new__(cls, swims: builtins.int) -> Animal.Bird: ...

    ...


def create_animal_df() -> pl.DataFrame: ...
