//! Wire types for the craftpath job API.
//!
//! Generated by `prost-build` (binary protobuf) and `pbjson-build` (canonical
//! proto3 JSON via serde) from the schemas in `/proto/craftpath/v1`. The same
//! generated type therefore serves both the `application/x-protobuf` and the
//! `application/json` encodings and they can never drift apart.

pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/craftpath.v1.rs"));
    include!(concat!(env!("OUT_DIR"), "/craftpath.v1.serde.rs"));
}

pub mod convert;

pub use convert::ConvertError;
