apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftpath.fullname" . }}-rest
  labels:
    {{- include "craftpath.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
spec:
  type: {{ .Values.rest.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "craftpath.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rest
  ports:
    - name: http
      port: {{ .Values.rest.service.port }}
      targetPort: http
